CC		= gcc

CFLAGS	= -Werror -ansi -g -c
LDFLAGS	= -g -static


.PHONY: all clean

all:   1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17
	
1: 8.1.o
	$(CC) $(LDFLAGS) -o $@ $<
	
2: 8.2.o
	$(CC) $(LDFLAGS) -o $@ $<
	
3: 8.3.o
	$(CC) $(LDFLAGS) -o $@ $<
	
4: 8.4.o
	$(CC) $(LDFLAGS) -o $@ $<
	
5: 8.5.o
	$(CC) $(LDFLAGS) -o $@ $<
	
6: 8.6.o
	$(CC) $(LDFLAGS) -o $@ $<
	
7: 8.7.o
	$(CC) $(LDFLAGS) -o $@ $<
	
8: 8.8.o
	$(CC) $(LDFLAGS) -o $@ $<
	
9: 8.9.o
	$(CC) $(LDFLAGS) -o $@ $<
	
10: 8.10.o
	$(CC) $(LDFLAGS) -o $@ $<
	
11: 8.11.o
	$(CC) $(LDFLAGS) -o $@ $<
	
12: 8.12.o
	$(CC) $(LDFLAGS) -o $@ $<
	
13: 8.13.o
	$(CC) $(LDFLAGS) -o $@ $<
	
14: 8.14.o
	$(CC) $(LDFLAGS) -o $@ $<
	
15: 8.15.o
	$(CC) $(LDFLAGS) -o $@ $<
	
16: 8.16.o
	$(CC) $(LDFLAGS) -o $@ $<
	
17: 8.17.o
	$(CC) $(LDFLAGS) -o $@ $<
	
%o:%c
	$(CC) $(CFLAGS) $<

clean:
	-del *.o 
#	-del *.a 
#	-del *.dll
	-del *.exe 
#	-del *.def