CC		= cl 
CFLAGS	= /nologo /Zi /Za /MTd /Od /TC

all : 1 2 3 4 5 6 7 8 9 10 11

1 : 5.1.c
	$(CC) $(CFLAGS) /Fe$@ $?
	
2 : 5.2.c
	$(CC) $(CFLAGS) /Fe$@ $?
	
3 : 5.3.c
	$(CC) $(CFLAGS) /Fe$@ $?
	
4 : 5.4.c
	$(CC) $(CFLAGS) /Fe$@ $?
	
5 : 5.5.c
	$(CC) $(CFLAGS) /Fe$@ $?
	
6 : 5.6.c
	$(CC) $(CFLAGS) /Fe$@ $?
	
7 : 5.7.c
	$(CC) $(CFLAGS) /Fe$@ $?
	
8 : 5.8.c
	$(CC) $(CFLAGS) /Fe$@ $?

9 : 5.9.c
	$(CC) $(CFLAGS) /Fe$@ $?
	
10 : 5.10.c
	$(CC) $(CFLAGS) /Fe$@ $?
	
11 : 5.11.c
	$(CC) $(CFLAGS) /Fe$@ $?
	
clean : 
	-del *.ilk
	-del *.obj
	-del *.pdb
	-del *.exe